"""Stage 6: per-question rollup with representative, source-linked quotes. Phase 1 implementation."""

from __future__ import annotations

import json
import logging
from pathlib import Path

import pandas as pd

from scrapper import DIAGNOSTIC_QUESTIONS

log = logging.getLogger(__name__)

MAX_QUOTES_PER_THEME = 3
MAX_THEMES_PER_QUESTION = 8


def run(clusters_path: Path, reviews_path: Path, out_dir: Path) -> None:
    """Group labeled clusters by diagnostic question; write diagnosis.json + diagnosis.md."""
    clusters = json.loads(clusters_path.read_text(encoding="utf-8"))
    df = pd.read_parquet(reviews_path)
    id_to_review = {row["id"]: row for _, row in df.iterrows()}

    diagnosis: dict[int, dict] = {}

    for qid, q_text in DIAGNOSTIC_QUESTIONS.items():
        matching = [c for c in clusters if qid in c.get("diagnostic_questions", [])]
        matching_sorted = sorted(matching, key=lambda c: c["size"], reverse=True)[:MAX_THEMES_PER_QUESTION]

        themes_out = []
        for cluster in matching_sorted:
            quotes = []
            for rid in cluster.get("representative_quote_ids", [])[:MAX_QUOTES_PER_THEME]:
                row = id_to_review.get(rid)
                if row is None:
                    continue
                quotes.append({
                    "text": str(row["text"])[:500],
                    "source": str(row.get("source", "")),
                    "source_url": str(row.get("source_url", "")),
                    "rating": row.get("rating"),
                    "created_at": str(row.get("created_at", "")),
                })

            themes_out.append({
                "theme_label": cluster["label"],
                "summary": cluster["summary"],
                "cluster_id": cluster["cluster_id"],
                "volume": cluster["size"],
                "confidence": cluster.get("confidence", "medium"),
                "quotes": quotes,
            })

        total_volume = sum(c["size"] for c in matching_sorted)
        diagnosis[qid] = {
            "question_id": qid,
            "question": q_text,
            "theme_count": len(themes_out),
            "total_volume": total_volume,
            "themes": themes_out,
        }

    out_dir.mkdir(parents=True, exist_ok=True)

    # JSON
    json_out = out_dir / "diagnosis.json"
    json_out.write_text(json.dumps(diagnosis, indent=2, ensure_ascii=False), encoding="utf-8")
    log.info("Wrote %s", json_out)

    # Markdown (deck-ready)
    md_out = out_dir / "diagnosis.md"
    md_out.write_text(_build_markdown(diagnosis), encoding="utf-8")
    log.info("Wrote %s", md_out)

    # Run manifest
    manifest = {
        "total_reviews": len(df),
        "total_clusters": len(clusters),
        "questions_covered": [qid for qid, q in diagnosis.items() if q["theme_count"] > 0],
    }
    (out_dir / "run_manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")


def query(question_id: int, reports_dir: Path) -> dict:
    """Reviewer-facing: return themes + quotes for one diagnostic question."""
    path = reports_dir / "diagnosis.json"
    if not path.exists():
        raise FileNotFoundError(
            f"diagnosis.json not found in {reports_dir}. Run the full pipeline first:\n"
            "  scrapper run all"
        )
    data = json.loads(path.read_text(encoding="utf-8"))
    key = str(question_id)
    if key not in data:
        raise KeyError(f"Question {question_id} not found in diagnosis. Valid: 1-6")
    return data[key]


def _build_markdown(diagnosis: dict) -> str:
    lines = [
        "# Spotify Discovery Diagnosis",
        "",
        "> Auto-generated by Scrapper pipeline. Every quote links to its original source.",
        "",
    ]
    for qid in sorted(diagnosis.keys()):
        q = diagnosis[qid]
        lines.append(f"## Q{qid}. {q['question']}")
        lines.append(f"*{q['theme_count']} themes · {q['total_volume']} matching reviews*")
        lines.append("")
        for theme in q["themes"]:
            lines.append(f"### {theme['theme_label']}")
            lines.append(f"> {theme['summary']}")
            lines.append(f"*Volume: {theme['volume']} reviews · Confidence: {theme['confidence']}*")
            lines.append("")
            for quote in theme["quotes"]:
                source_label = quote["source"].replace("_", " ").title()
                link = quote.get("source_url", "")
                rating = f" ★{quote['rating']}" if quote.get("rating") else ""
                lines.append(f'> "{quote["text"]}"')
                lines.append(f"> — [{source_label}{rating}]({link})")
                lines.append("")
        lines.append("---")
        lines.append("")
    return "\n".join(lines)
